In [1]:
import numpy as np
import pandas as pd
import os

In [3]:
curr_path = os.getcwd()
datasets_folder = os.path.join(curr_path, 'Datasets')
dataset_file = os.path.join(datasets_folder, 'MIPT_hackathon_dataset.csv')
os.path.exists(dataset_file)

True

In [42]:
'''Таблица на самом деле вполне нормальная, просто необходимо уточнить разделитель (sep) и квалификатор текста (quotechar).
Например, состав заказа прописан в виде нескольких переносов строк с пунктами, двоеточиями, запятыми внутри и т. д.,
однако этот столбец целиком обособлен от всех остальных двойными кавычками. Бонусная информация: судя по всему, последним пунктом заказа
всегда значится Доставка (Артикул: 1 ...). ts - timestamp (полагаю, в секундах с 01.01.1970). Наверное, время с точностью до секунды
стоит привести в формат '%Y-%m-%d %H:%M:%S'
'''
dataset = pd.read_csv(dataset_file, sep = ',', quotechar='"', parse_dates = True, date_format = '%Y-%m-%d')
dataset.head(5)

,lead_id,sale_ts,sale_date,buyout_flag,outcome_unknown,handed_to_delivery_ts,issued_or_pvz_ts,received_ts,rejected_ts,returned_ts,...,lead_Дата перехода Передан в доставку,lead_Ответственный за доставку,lead_Нумерация сделки,lead_Дата приобретения изделия,lead_Поиск товаров GoSklad,lead_ACTUAL-FORMAT,lead_BANNER-SIZES,lead_WIDTH,lead_HEIGHT,lead_Список товаров GoSklad
0,LEAD_0217,1761974724,2025-11-01,True,False,1.762243e+09,1.762505e+09,1.762602e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LEAD_0220,1761975068,2025-11-01,True,False,1.762243e+09,1.762690e+09,1.762789e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LEAD_0058,1761976628,2025-11-01,True,False,1.762252e+09,1.762682e+09,1.762749e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LEAD_0221,1761976896,2025-11-01,False,False,1.762243e+09,1.762527e+09,NaN,1.764142e+09,1.764676e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LEAD_0218,1761977233,2025-11-01,True,False,1.762245e+09,1.762574e+09,1.762583e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
def epSec2Datetime(df):
    for col in df.columns.tolist():
        df[col] = pd.to_datetime(df[col], unit = 's')
    return df
def datetime2EpSec(df):
    for col in df.columns.tolist():
        df[col] = (df[col] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')
    return df

In [45]:
from pprint import pprint
columns = dataset.columns.tolist()
secCols = [i for i in columns if ('_ts' in i) or ('_at' in i) or ('Дата' in i)]
#pprint(secCols)

In [46]:
dataset[secCols] = epSec2Datetime(dataset[secCols])

C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')
C:\Users\andra\AppData\Local\Temp\ipykernel_16444\4082436369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], unit = 's')

In [48]:
dataset

,lead_id,sale_ts,sale_date,buyout_flag,outcome_unknown,handed_to_delivery_ts,issued_or_pvz_ts,received_ts,rejected_ts,returned_ts,...,lead_Дата перехода Передан в доставку,lead_Ответственный за доставку,lead_Нумерация сделки,lead_Дата приобретения изделия,lead_Поиск товаров GoSklad,lead_ACTUAL-FORMAT,lead_BANNER-SIZES,lead_WIDTH,lead_HEIGHT,lead_Список товаров GoSklad
0,LEAD_0217,2025-11-01 05:25:24,2025-11-01,True,False,2025-11-04 07:54:16,2025-11-07 08:36:40,2025-11-08 11:40:35,NaT,NaT,...,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1,LEAD_0220,2025-11-01 05:31:08,2025-11-01,True,False,2025-11-04 07:54:21,2025-11-09 11:58:22,2025-11-10 15:33:17,NaT,NaT,...,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
2,LEAD_0058,2025-11-01 05:57:08,2025-11-01,True,False,2025-11-04 10:18:44,2025-11-09 09:47:21,2025-11-10 04:29:44,NaT,NaT,...,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
3,LEAD_0221,2025-11-01 06:01:36,2025-11-01,False,False,2025-11-04 07:54:25,2025-11-07 14:44:38,NaT,2025-11-26 07:32:23,2025-12-02 11:52:02,...,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
4,LEAD_0218,2025-11-01 06:07:13,2025-11-01,True,False,2025-11-04 08:37:49,2025-11-08 04:00:46,2025-11-08 06:23:13,NaT,NaT,...,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5378,LEAD_5357,2026-02-28 16:17:04,2026-02-28,True,False,2026-03-02 14:56:05,2026-03-05 08:55:12,2026-03-05 11:34:08,NaT,NaT,...,2026-03-01 21:00:00,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
5379,LEAD_4490,2026-02-28 16:22:05,2026-02-28,True,False,2026-03-02 12:24:42,2026-03-07 13:02:37,2026-03-14 13:04:35,NaT,NaT,...,2026-03-01 21:00:00,DLV_0002,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
5380,LEAD_5333,2026-02-28 16:22:05,2026-02-28,True,False,2026-03-02 09:55:25,2026-03-05 11:02:53,2026-03-06 13:20:56,NaT,NaT,...,2026-03-01 21:00:00,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
5381,LEAD_5383,2026-02-28 17:27:04,2026-02-28,True,False,2026-03-02 14:51:45,2026-03-04 08:19:33,2026-03-04 09:36:37,NaT,NaT,...,2026-03-01 21:00:00,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
5382,LEAD_5335,2026-02-28 17:30:11,2026-02-28,True,False,2026-03-02 14:20:36,2026-03-06 13:45:18,2026-03-10 11:02:51,NaT,NaT,...,2026-03-01 21:00:00,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN